### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by RealendergamerYt** [GamerGambit/cw2-fas2-weapon-attachment-vendor#5] opened 2024-08-18 01:52 UTC
[attachmentvendor] addons/attachmentvendor/lua/attachment_vendor/shared/sh_attachment_vendor_ext.lua:79: attempt to index field 'AttachmentTable' (a nil value)
    1. isARCCWAttachment - addons/attachmentvendor/lua/attachment_vendor/shared/sh_attachment_vendor_ext.lua:79
        2. v - addons/attachmentvendor/lua/autorun/server/sv_attachment_vendor.lua:20
            3. unknown - lua/includes/modules/hook.lua:96

**Comment by GamerGambit** [comment] 2024-08-18 02:13
Thanks for reporting this. Can you please tell me which weapon packs you are using so I can test this out?

**Comment by RealendergamerYt** [comment] 2024-08-18 15:37
cw2.0

**Comment by GamerGambit** [comment] 2024-08-18 22:33
I'm not able to reproduce this error. Are you able to tell me which gamemode you are using and which other addons you have? If the only weapon pack you have is cw2.0 then this shouldn't be an issue unless you are using a modified version of the Attachment Vendor addon or the gamemode or other addon is interfering with it.

**Comment by GamerGambit** [comment] 2024-08-30 23:03
I'm still not able to reproduce this error. Without more information I'll have to close this ticket.

**Closed** 2024-09-10 04:12 UTC
